### ISSUE TITLE
Cannot use pip 10 to install tg-hammer

### ISSUE THREAD

**Issue by dforz** [thorgate/tg-hammer#21]
Downgrading to 9 works but actually fixing it looks like a simple fix.

[See this SO issue
](https://stackoverflow.com/questions/25192794/no-module-named-pip-req)

```
Collecting tg-hammer
  Downloading https://files.pythonhosted.org/packages/92/5e/a618ff7f4eeeff6f819ff7d7218d3ab89508859357b96e466449b1d288f4/tg-hammer-0.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zz/ym6pb_c906ncdfkwckj47zfm0000gn/T/pip-install-4w94f_pw/tg-hammer/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: cannot import name 'parse_requirements'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zz/ym6pb_c906ncdfkwckj47zfm0000gn/T/pip-install-4w94f_pw/tg-hammer/
```

**Comment by Jyrno42** [comment]
Should be resolved by #22 released under 0.6.6.

- https://github.com/thorgate/tg-hammer/releases/tag/0.6.6
